---
title: "Code Book"
author: "Lauren Purdy"
date: "6/19/2021"
output: html_document
---

## Codebook  
  
The `run_analysis.R` script performs the data preparation followed by the 5 steps required by the project.  
  
1. **Download the dataset**  
* Dataset downloaded and extracted under the folder called `UCI HAR Dataset`  
  
2. **Assign data to variables**  
* `features` <- `features.txt`: 561 rows, 2 cols
* `activities` <- `activity_labels.txt`: 6 rows, 2 cols
*  `subject_test` <- `test/subject_test.txt`: 2947 rows, 1 col
* `x_test` <- `test/X_test.txt`: 2947 rows, 1 col
* `y_test` <- `test/y_test.txt`: 2947 rows, 1 col
* `subject train` <- `test/subject_train.txt`: 7352 rows, 1 col
* `x_train` <- `test/X_train.txt`: 7352 rows, 1 col
* `y_train` <- `test/y_train.txt`: 7352 rows, 1 col  

3. **Merge the datasets**  
* `x` (10299 rows, 561 cols) is created by merging `x_train` and `x_test` using rbind()
* `y` (10299 rows, 561 cols) is created by merging`y_train` and `y_test` using rbind()
* `subject` (10299 rows, 1 col) is created by merging `subject_train` and `subject_test` using rbind()
* `Merged_Data` (10299 rows, 563 cols) is created by merging `subject`, `y` and `x` using cbind()  

4. **Extract mean and SD for each measurement**  
* `Tidy` (10299 rows, 88 cols) is created by subsetting `Merged_Data`, selecting only columns `subject`, `code`, and the `mean` and `std`  
5. **Name the activities**  
* Numbers in `code` col of the `Tidy` dataset are replaced with corresponding activities from the 2nd col of the `activities` variable  

6. **Label with descriptive variable names**  
* `code` col in `Tidy` renamed to `activities`
* `Acc` replaced by `Accelerometer`
* `Gyro` replaced by `Gyroscope`
* `BodyBody` replaced by `Body`
* `Mag` replaced by `Magnitude`
* `f` cols replaced by `Frequency`
* `t` cols replaced by `Time`  

7. **Create a tidy data set with the averages for each activity and subject**  
* `GoodData` (180 rows, 88 cols) created by summarizing `Tidy` 
* Export `GoodData` into `GoodData.txt` file
``